
# while_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'C9B80A14BAEB7A28521EE7A0FAA70F52'
    
_lr_action_items = {'THEN':([15,24,],[-10,33,]),'RETURN':([0,9,23,33,40,46,],[1,1,1,1,1,1,]),'OP_SEMI':([6,7,8,10,13,14,15,19,20,26,27,28,31,38,43,44,45,47,48,50,],[-9,-7,-3,23,-21,-12,-10,-11,-22,-14,-13,-8,-6,-23,-15,-17,-16,-5,-18,-4,]),'ASSERT':([0,9,23,33,40,46,],[2,2,2,2,2,2,]),'LCURLY':([15,16,],[-10,25,]),'WHILE':([0,9,23,33,40,46,],[3,3,3,3,3,3,]),'FORMULA':([2,3,5,11,21,25,],[15,15,15,15,15,15,]),'NEW':([17,],[26,]),'NULL':([17,37,],[27,44,]),'RPAREN':([6,7,8,10,13,14,15,19,20,22,26,27,28,31,32,38,41,42,43,44,45,47,48,50,51,],[-9,-7,-3,-1,-21,-12,-10,-11,-22,31,-14,-13,-8,-6,-2,-23,48,-19,-15,-17,-16,-5,-18,-4,-20,]),'RCURLY':([15,34,],[-10,40,]),'ASSUME':([0,9,23,33,40,46,],[5,5,5,5,5,5,]),'OP_COMMA':([6,42,],[-9,49,]),'OP_PERIOD':([4,6,28,],[18,-9,36,]),'IDENTIFIER':([0,1,9,17,18,23,33,35,36,37,40,46,49,],[6,6,6,6,6,6,6,6,6,6,6,6,6,]),'$end':([6,7,8,10,12,13,14,15,19,20,26,27,28,31,32,38,43,44,45,47,48,50,],[-9,-7,-3,-1,0,-21,-12,-10,-11,-22,-14,-13,-8,-6,-2,-23,-15,-17,-16,-5,-18,-4,]),'SKIP':([0,9,23,33,40,46,],[7,7,7,7,7,7,]),'OP_ASSIGN':([4,6,29,],[17,-9,37,]),'RBRACK':([15,30,],[-10,38,]),'ELSE':([6,7,8,13,14,15,19,20,26,27,28,31,38,39,43,44,45,47,48,50,],[-9,-7,-3,-21,-12,-10,-11,-22,-14,-13,-8,-6,-23,46,-15,-17,-16,-5,-18,-4,]),'LPAREN':([0,6,9,23,28,33,40,46,],[9,-9,9,9,35,9,9,9,]),'IF':([0,9,23,33,40,46,],[11,11,11,11,11,11,]),'LBRACK':([6,7,8,13,14,15,19,20,26,27,28,38,43,44,45,48,],[-9,-7,21,-21,-12,-10,-11,-22,-14,-13,-8,-23,-15,-17,-16,-18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cmd':([0,9,23,],[12,22,32,]),'ids':([35,49,],[41,51,]),'stmt':([0,9,23,33,40,46,],[8,8,8,8,8,8,]),'annotation':([8,],[20,]),'formula':([2,3,5,11,21,25,],[14,16,19,24,30,34,]),'cmdf':([0,9,23,33,40,46,],[10,10,10,39,47,50,]),'id':([0,1,9,17,18,23,33,35,36,37,40,46,49,],[4,13,4,28,29,4,4,42,43,45,4,4,42,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> cmd","S'",1,None,None,None),
  ('cmd -> cmdf','cmd',1,'p_command_singl','while_fe.py',79),
  ('cmd -> cmdf OP_SEMI cmd','cmd',3,'p_command_seq','while_fe.py',83),
  ('cmdf -> stmt','cmdf',1,'p_command_atom','while_fe.py',87),
  ('cmdf -> IF formula THEN cmdf ELSE cmdf','cmdf',6,'p_command_if_then_else','while_fe.py',91),
  ('cmdf -> WHILE formula LCURLY formula RCURLY cmdf','cmdf',6,'p_command_while','while_fe.py',95),
  ('cmdf -> LPAREN cmd RPAREN','cmdf',3,'p_command_block','while_fe.py',99),
  ('stmt -> SKIP','stmt',1,'p_stmt_skip','while_fe.py',103),
  ('stmt -> id OP_ASSIGN id','stmt',3,'p_stmt_assign','while_fe.py',107),
  ('id -> IDENTIFIER','id',1,'p_id','while_fe.py',111),
  ('formula -> FORMULA','formula',1,'p_formula','while_fe.py',115),
  ('stmt -> ASSUME formula','stmt',2,'p_assume_assert','while_fe.py',123),
  ('stmt -> ASSERT formula','stmt',2,'p_assume_assert','while_fe.py',124),
  ('stmt -> id OP_ASSIGN NULL','stmt',3,'p_stmt_assign_null','while_fe.py',133),
  ('stmt -> id OP_ASSIGN NEW','stmt',3,'p_stmt_allocate','while_fe.py',137),
  ('stmt -> id OP_ASSIGN id OP_PERIOD id','stmt',5,'p_stmt_field_get','while_fe.py',141),
  ('stmt -> id OP_PERIOD id OP_ASSIGN id','stmt',5,'p_stmt_field_set','while_fe.py',145),
  ('stmt -> id OP_PERIOD id OP_ASSIGN NULL','stmt',5,'p_stmt_field_set_null','while_fe.py',149),
  ('stmt -> id OP_ASSIGN id LPAREN ids RPAREN','stmt',6,'p_stmt_call','while_fe.py',157),
  ('ids -> id','ids',1,'p_list_of_args_singl','while_fe.py',161),
  ('ids -> id OP_COMMA ids','ids',3,'p_list_of_args_cons','while_fe.py',164),
  ('stmt -> RETURN id','stmt',2,'p_stmt_return','while_fe.py',168),
  ('stmt -> stmt annotation','stmt',2,'p_stmt_annotated','while_fe.py',172),
  ('annotation -> LBRACK formula RBRACK','annotation',3,'p_annotation','while_fe.py',176),
]
