python $src/relaxed_trace_analyzer.py -u $benchmarks/sll-concat.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/sll-concat.imp -n=10
python $src/relaxed_trace_analyzer.py    $benchmarks/safety-only/sll-concat.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/sll-create.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/sll-create.imp -n=10
python $src/relaxed_trace_analyzer.py    $benchmarks/safety-only/sll-create.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/sll-delete-at.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/sll-delete-at.imp -n=10
python $src/relaxed_trace_analyzer.py    $benchmarks/safety-only/sll-delete-at.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/sll-deleteAll.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/sll-deleteAll.imp -n=10
python $src/relaxed_trace_analyzer.py    $benchmarks/safety-only/sll-deleteAll.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/sll-filter.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/sll-filter.imp -n=10
python $src/relaxed_trace_analyzer.py    $benchmarks/safety-only/sll-filter.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/sll-insert-at.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/sll-insert-at.imp -n=10
python $src/relaxed_trace_analyzer.py    $benchmarks/safety-only/sll-insert-at.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/sll-insert.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/sll-insert.imp -n=10
python $src/relaxed_trace_analyzer.py    $benchmarks/safety-only/sll-insert.imp -n=10
# (>300s) python $src/relaxed_trace_analyzer.py -u $benchmarks/sll-merge.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/sll-merge.imp -n=10
python $src/relaxed_trace_analyzer.py    $benchmarks/safety-only/sll-merge.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/sll-reverse.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/sll-reverse.imp -n=10
python $src/relaxed_trace_analyzer.py    $benchmarks/safety-only/sll-reverse.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/sll-split.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/sll-split.imp -n=10
python $src/relaxed_trace_analyzer.py    $benchmarks/safety-only/sll-split.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/uf-find.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/uf-find.imp -n=10
python $src/relaxed_trace_analyzer.py    $benchmarks/safety-only/uf-find.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/uf-union.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/uf-union.imp -n=10
# (TO) python $src/relaxed_trace_analyzer.py $benchmarks/safety-only/uf-union.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/sll-sorted-insert.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/sll-sorted-insert.imp -n=10
python $src/relaxed_trace_analyzer.py    $benchmarks/safety-only/sll-sorted-insert.imp -n=10
# (>300s) python $src/relaxed_trace_analyzer.py -u $benchmarks/sll-sorted-merge.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/sll-sorted-merge.imp -n=10
python $src/relaxed_trace_analyzer.py    $benchmarks/safety-only/sll-sorted-merge.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/sll-bubble-sort.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/sll-bubble-sort.imp -n=10
python $src/relaxed_trace_analyzer.py    $benchmarks/safety-only/sll-bubble-sort.imp -n=10
# (>2000s) python $src/relaxed_trace_analyzer.py -u $benchmarks/sll-insertion-sort.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/sll-insertion-sort.imp -n=10
# (TO) python $src/relaxed_trace_analyzer.py $benchmarks/safety-only/sll-insertion-sort.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/dll-create.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/dll-create.imp -n=10
python $src/relaxed_trace_analyzer.py    $benchmarks/safety-only/dll-create.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/dll-delete.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/dll-delete.imp -n=10
# (>300s) python $src/relaxed_trace_analyzer.py $benchmarks/safety-only/dll-delete.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/dll-insert-at.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/dll-insert-at.imp -n=10
# (>300s) python $src/relaxed_trace_analyzer.py $benchmarks/safety-only/dll-insert-at.imp -n=10
# (>600s) python $src/relaxed_trace_analyzer.py -u $benchmarks/sll-nested-flatten.imp -n=10
# (>300s) python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/sll-nested-flatten.imp -n=10
python $src/relaxed_trace_analyzer.py    $benchmarks/safety-only/sll-nested-flatten.imp -n=10
# (>300s) python $src/relaxed_trace_analyzer.py -u $benchmarks/sll-nested-split.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/sll-nested-split.imp -n=10
python $src/relaxed_trace_analyzer.py    $benchmarks/safety-only/sll-nested-split.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/sll-shared-delete.imp -n=10
python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/sll-shared-delete.imp -n=10
# (TO) python $src/relaxed_trace_analyzer.py $benchmarks/safety-only/sll-shared-delete.imp -n=10
# Lena: sll-ladder files are missing
# python $src/relaxed_trace_analyzer.py -u $benchmarks/sll-ladder.imp -n=10
# python $src/relaxed_trace_analyzer.py -u $benchmarks/safety-only/sll-ladder.imp -n=10
# python $src/relaxed_trace_analyzer.py    $benchmarks/safety-only/sll-ladder.imp -n=10
